
#include <ansi.h>
#include <task.h>

// 数组：标准提示信息 -- [随意]
mapping TipsTable = ([
             "Hoa Mai" :   "Loại hoa này ở "HIR" Đường Gia Trang Viên chỗ Loan Đạo"NOR" có không ít, cơ mà nguy hiểm lắm.",
             "Hoa Lan" :   ""HIR"Đường Gia Trang Viên "NOR" khắp nơi đều trồng Hoa Lan, ngươi tới đó hẳn sẽ có chút thu hoạch.",
             "Văn Trúc" :   "Đây là một loại thực vật tương đối hiếm thấy……nghe nói "HIR"Thích Khách Nữ Tính "NOR" rất thích đeo loại thực vật này trên người làm bùa hên.",
             "Hoa Cúc" :   "Loại hoa này ở khắp nơi, ở "HIR" Thủ Dương Sơn"NOR" cũng rất nhiều.",
             "Hoa Hồng" :   "Ngay cả mấy thứ côn đồ như mấy thằng "HIR"Công Tử Bột "NOR" cũng rất thích loại hoa này, ngươi có thể thử tìm xem.",
             "Hoa Lài" :   "Loại hoa này ở "HIR" Trường Bạch Sơn"NOR" hình như có rất nhiều đấy?",
             "Hoa Mẫu Đơn" :   "Loại hoa này ở "HIR" Trường Bạch Sơn"NOR" hình như có rất nhiều đấy?",
             "Hoa Đào" :   "Ở "HIR"Đào Hoa Nguyên Thôn"NOR" tràn đầy loại hoa này khắp nơi.",
             "Hoa Sơn Trà" :   "Loại hoa này ở "HIR" Trường Bạch Sơn"NOR" hình như có rất nhiều đấy?",
             "Hoa Thược Dược" :   "Thược Dược Hoa có thể tìm thấy ở "HIR"Vận Mộng Cốc"NOR" rất nhiều.",
             "Hoa Khiên Ngưu" :   "Khiên Ngưu Hoa hình như có thể tìm ở "HIR"Vân Mộng Cốc"NOR" rất nhiều.",
             "Hoa Đại Hồng" :   "Đi "HIR"Triều Dương Phong"NOR" hoặc "HIR"Hoa Sơn"NOR" quanh quanh đó sẽ thấy.",
             "Hoa Thủy Tiên" :   "Ngươi đi "HIR"Động Đình Hồ"NOR" quanh đấy sẽ thấy được thứ ngươi cần.",
             "Hoa Hải Đường" :   "Loại hoa này hình như ở "HIR" Cầu Cửu Khúc"NOR" sinh trưởng rất nhiều",
             "Hoa Bách Hợp" :   "Loại hoa này giống như ở "HIR" Trường Bạch Sơn"NOR" có rất nhiều.",
             "Hoa Đinh Hương" :   "Đi "HIR"Thúy Hoa Sơn"NOR" hoặc "HIR"Thủ Dương Sơn"NOR" chắc chắn sẽ có.",
             "Hồng Trà" :   "Nghe nói "HIR"Hoa Báo Yêu"NOR" thích đem thứ trà này để uống.",
             "Lục Trà" :   "Nghe nói "HIR"Hoa Báo Yêu"NOR" thích đem thứ trà này để uống.",
             "Hoa Trà Lài" :   ""HIR"Yên Quốc"NOR" binh lính rất thích uống loại trà này, hãy tới "HIR"Yên Trường Thành"NOR" để coi xin họ thế nào?",
             "Trà Phổ Nhị" :   ""HIR"Yên Quốc "NOR" binh sĩ rất thích loại trà này, ngươi đến "HIR"Yên Trường Thành"NOR" hỏi xem họ có cho ta một ít không?",
             "Trà Quan Thế Âm" :   "Sở Quốc binh sĩ rất thích loại trà này, ngươi tới "HIR"Sở Phương Thành"NOR" xem họ muốn sao?",
             "Trà Long Tỉnh" :   "Nghe qua "HIR"Sài Cẩu"NOR" vô cùng thích trà Long Tỉnh, ngươi có thể đi tìm.",
             "Trà Vân Vụ" :   "Sở Quốc binh sĩ rất thích loại trà này, ngươi tới "HIR"Sở Phương Thành"NOR" xem họ muốn sao?",
             "Lá Trà Quan Thế Âm" :   "Sở Quốc binh sĩ rất thích loại trà này, ngươi tới "HIR"Sở Phương Thành"NOR" xem họ muốn sao?",
             "Lá Trà Vân Vụ" :   "Sở Quốc binh sĩ rất thích loại trà này, ngươi tới "HIR"Sở Phương Thành"NOR" xem họ muốn sao?",
             "Rượu Đế" :   ""HIR"Triệu Quốc "NOR"cùng"HIR" Sở Quốc"NOR" binh sĩ tương đối thích loại rượu này.",
             "Hoàng Tửu" :   ""HIR"Triệu Quốc "NOR"cùng"HIR" Sở Quốc"NOR" binh sĩ tương đối thích loại rượu này.",
             "Lão Tửu" :   ""HIR"Triệu Quốc "NOR"cùng"HIR" Sở Quốc"NOR" binh sĩ tương đối thích loại rượu này.",
             "Thiên Dao Tửu" :   ""HIR"Vô Định Hà"NOR" là nơi Thổ Phỉ Côn Đồ rất thích loại rượu này.",
             "Phần Tửu" :   "Rượu này thường ở "HIR"Triệu Trường Thành"NOR" mới có thể tìm được.",
             "Đỗ Khang Tửu" :   ""HIR"Nhạn Môn Quan"NOR" ở đấy bọn "HIR"Cường Đạo"NOR" có loại rượu giống như vậy.",
             "Nữ Nhi Hồng" :   ""HIR"Nhạn Môn Quan"NOR" ở đấy bọn "HIR"Cường Đạo"NOR" có loại rượu giống như vậy.",
             "Thủy Đạo" :   ""HIR"Gà Con"NOR" trên người có nhiều lắm phải ko?",
             "Mạch Tử" :   ""HIR"Gà Con"NOR" trên người có nhiều lắm phải ko?",
             "Ngọc Mễ" :   ""HIR"Gà Con"NOR" trên người có nhiều lắm phải ko?",
             "Tiểu Mễ" :   ""HIR"Gà Con"NOR" trên người có nhiều lắm phải ko?",
             "Cao Lương" :   "Ta nhớ ở "HIR"Vân Mộng Cốc"NOR" có thể tìm tới cao lương .",
             "Đông Qua" :   "Đông qua cùng nam dưa đều là "HIR"Heo Rừng"NOR" thích ăn thức ăn .",
             "Nam Qua" :   "Đông qua cùng nam dưa đều là "HIR"Heo Rừng"NOR" thích ăn thức ăn .",
             "Hoàng Qua" :   "Hoàng dưa có thể tìm ở trên người"HIR"Ngưu đầu quái"NOR".",
             "Cà Rốt" :   "Ngươi đi tìm "HIR"Thỏ Trắng"NOR" đòi đi.",
             "Bạch Thái" :   "Ngươi đi tìm "HIR"Thỏ Trắng"NOR" đòi đi.",
             "Rau Cỏ" :   "Ngươi đi tìm "HIR"Thỏ Trắng"NOR" đòi đi.",
             "Phiên Thự" :   "Sở quốc : Binh lính Sở Quốc giống như cũng đem "HIR" Lần thự"NOR" mang ở trên người làm lương khô để ăn.",
             "Sơn Dược" :   "Ta nhớ ở "HIR"Hoa Sơn"NOR" một dãy có thể tìm tới ……",
             "Liên Ngẫu" :   "Ngươi đi "HIR"Đông Hải Chi Tân"NOR" quan sát một lúc có thể phát hiện được gì đó...",
             "Gia Tử" :   "Giống như "HIR"Đào Hoa Nguyên Thôn"NOR" một dãy thì có không ít .",
             "Trúc Duẩn" :   ""HIR"Trường Bạch Sơn"NOR" một dãy sinh trưởng không ít trúc duẩn đi ?",
             "Ma Cô" :   ""HIR"Tiểu Thỏ Tử"NOR" cũng thích ăn ma cô .",
             "Hạt Đậu" :   ""HIR"Kiến Con"NOR" rất thích đem mấy cái này đi giấu.",
             "Đậu Nành" :   ""HIR"Kiến Con"NOR" rất thích đem mấy cái này đi giấu.",
             "Biển Đậu" :   ""HIR"Kiến Con"NOR" rất thích đem mấy cái này đi giấu.",
             "Hoa Sinh" :   ""HIR"Kiến Con"NOR" rất thích đem mấy cái này đi giấu.",
             "Chi Ma" :   ""HIR"Kiến Con"NOR" rất thích đem mấy cái này đi giấu.",
             "Du Thái Tử" :   "Ta nhớ "HIR"Con Nhện"NOR" trên người có thời điểm sẽ dính một ít du món ăn tử .",
             "Hột Tiêu" :   "Ngươi có thể ăn cay sao ? ta biết "HIR"Triệu Quốc"NOR" có người tương đối có thể ăn cay như ngươi.",
             "Hành" :   ""HIR"Yên Quốc"NOR" tiểu mao đầu binh lính giống như đã hết sức thích đại hành .",
             "Tỏi" :   "Ở "HIR"Phụ Cận Thái Sơn"NOR" hẳn có thể tìm được đại toán .",
             "Gừng" :   "Ở "HIR"Đại biệt sơn phụ cận"NOR" không chừng có thể tìm được .",
             "Mật Ong" :   "Sào huyệt "HIR"Ong Mật"NOR" có rất nhiều .",
             "Thuốc Lá" :   ""HIR"Ánh sáng mặt trời ngọn núi "NOR""HIR"Phong Cẩu"NOR" rất thích cắn khói cỏ chạy loạn khắp nơi .",
             "Trứng Gà" :   "Nuôi "HIR"Gà"NOR" ở nông trường thì có không ít .",
             "Trứng Vịt" :   ""HIR"Đông Hải"NOR" một dãy hẳn có không ít đi ?",
             "Trứng Chim" :   "Nuôi "HIR"Gà"NOR" ở nông trường thì có không ít .",
             "Trứng Rùa" :   ""HIR"Đông Hải"NOR" một dãy hẳn có không ít đi ?",
             "Dưa Hấu" :   ""HIR"Heo Rừng"NOR" cũng rất thích ăn dưa hấu .",
             "Chuối" :   ""HIR"Khỉ Con "NOR" rất thích ăn Hương Tiêu, ngươi đi tìm "HIR"Khỉ Con"NOR" là sẽ tìm được Hương Tiêu.",
             "Trái Quýt" :   "Ta muốn ngươi hẳn đi "HIR"Thái Hồ"NOR" quan sát một chút.",
             "Trái Táo" :   ""HIR"Khỉ Con "NOR" rất thích ăn Táo, ngươi đi tìm "HIR"Khỉ Con"NOR" là sẽ tìm được.",
             "Trái Lê" :   ""HIR"Thái Sơn"NOR" thượng thì có không ít lê tử .",
             "Trái Đào" :   ""HIR"Khỉ Con "NOR" rất thích ăn Đào, ngươi đi tìm "HIR"Khỉ Con"NOR" là sẽ tìm được .",
             "Dâu" :   "Ta muốn muốn …… hẳn ở "HIR"Xích bích"NOR" một dãy có thể tìm được dương mai .",
             "Nho" :   ""HIR"Vân Mộng Cốc"NOR" thì có bồ đào .",
             "Long Nhãn" :   "Ta muốn "HIR"Hoa Sơn"NOR" hoặc là ánh sáng mặt trời phong hội có không ít .",
             "Vải" :   ""HIR"Động Đình Hồ"NOR" một dãy thì có không ít lệ chi .",
             "烧饼" :   "Ta nhớ "HIR"Ngưu đầu quái"NOR" sẽ đem thiêu bính mang Ở  trên người lấy làm lương khô để ăn .",
             "煎饼" :   "Ta tin "HIR"Côn Đồ"NOR" sẽ đem tiên bính mang Ở trên người .",
             "红豆糕" :   "Nghe nói một ít "HIR"Phi Tặc"NOR" tương đối thích loại này phong vị tiểu thực .",
             "Hạt Đậu糕" :   "Nghe nói một ít "HIR"Sài Cẩu"NOR" tương đối thích loại này phong vị tiểu thực .",
             "牛肉干" :   "Ta muốn một ít thịt bò, nghe nói "HIR"Ngưu đầu quái"NOR" sẽ phải đem thịt bò khô mang Ở  trên người ……",
             "烤肉串" :   "Ta muốn một ít thịt bò, nghe nói "HIR"Ngưu đầu quái"NOR" sẽ phải đem thịt bò khô mang Ở  trên người ……",
             "烤Phiên Thự" :   "Ta nhớ ở "HIR"Đông Hải"NOR" một dãy ăn rồi loại này tiểu thực .",
             "豆腐干" :   "Ta nhớ ở "HIR"Quế lăng"NOR" một dãy ăn rồi loại này tiểu thực .",
             "臭豆腐" :   ""HIR"Kênh Trịnh Quốc"NOR" khổ công cửa bình thường cũng ăn những thứ đồ này .",
             "炒瓜子" :   ""HIR"Kênh Trịnh Quốc"NOR" khổ công cửa bình thường cũng ăn những thứ đồ này .",
             "炒Hoa Sinh" :   ""HIR"Kênh Trịnh Quốc"NOR" khổ công cửa bình thường cũng ăn những thứ đồ này . ",
             "冰糖葫芦" :   "Ta nhớ ở bạch mã trang đã từng ăn rồi loại này tiểu thực .",
             "铁铲" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "锄头" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "铁犁" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "镰刀" :   "Tiêu diệt "HIR"Đường lang quái"NOR" nói không chừng phải nhận được một thanh lưỡi hái .",
             "钉耙" :   "Một ít "HIR"Ngưu đầu quái"NOR" sẽ đem đinh bá làm vũ khí của mình .",
             "草叉" :   "Một ít "HIR"Ngưu đầu quái"NOR" sẽ đem đinh bá làm vũ khí của mình .",
             "铁锤" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "木槌" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "凿子" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "刨子" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "锯子" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "簸箕" :   "Loại công cụ này hãy đi "HIR"Trịnh Quốc Cừ"NOR" để tìm nhé!",
             "小木桶" :   "Ta nhớ vật này có trên người "HIR"Ngưu đầu quái"NOR"……",
             "柱香" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "蜡烛" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "檀香" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "黄纸" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "纸钱" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "朱砂" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "法笔" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "小香炉" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "鹤嘴炉" :   "Chắc chắn rằng ở bên trong "HIR"Thiên Môn Trận"NOR" hoặc "HIR"Linh Cốc Động"NOR" có rất nhiều thứ này.",
             "铁锅" :   "Tiêu diệt "HIR"Quán trung yêu"NOR"  sẽ có một thiết oa rơi ra cũng không chừng .",
             "陶碗" :   "Tiêu diệt "HIR"Sài Cẩu"NOR" sẽ có một chén kiểu rơi ra.",
             "金碗" :   "Truyền thuyết "HIR"Quán trung yêu"NOR" có một kim chén, không biết có phải thật không nữa .",
             "竹筷" :   "Ở "HIR"Tân Thủ Thôn"NOR" có thể tìm được.",
             "银筷" :   "Nghe nói một số "HIR"Cuồng Đồ"NOR" sẽ đem từ trên người người khác cướp đoạt được ngân chiếc đũa tàng mang trên người mình .",
             "碟子" :   "Khổ Dịch "HIR"Kênh Trịnh Quốc"NOR"  trên người hẳn đều mang đi ?",
             "盘子" :   "Khổ Dịch "HIR"Kênh Trịnh Quốc"NOR" trên người hẳn đều mang đi ?",
             "勺子" :   "Khổ Dịch "HIR"Kênh Trịnh Quốc"NOR" trên người hẳn đều mang đi ?",
             "水瓢" :   ""HIR"Hà Binh"NOR" trên người sẽ mang theo bầu nước .",
             "菜刀" :   "Những tên "HIR"Côn Đồ"NOR" hay mang theo một thanh Thái Đao đó!",
             "剪刀" :   "Tiêu diệt "HIR"Đường Lang quái"NOR" thử đi, nói không chừng sẽ rơi ra đấy.",
             "茶壶" :   "Ta muốn tìm "HIR"Phi Tặc"NOR" vì trên người hắn nhất định có Bình Trà.",
             "打火石" :   "Ngươi đến "HIR"Linh Cốc Động"NOR" ắt hẳn sẽ tìm được Đá Đánh Lửa bên trong.",
             "胭脂" :   "Những thứ phấn mà bọn công tử bột giả "HIR"Lưu Manh"NOR") hay trét lên mặt, làm cho bản thân nam không ra nam nữ không ra nữ.",
             "水粉" :   "Những thứ phấn mà bọn công tử bột giả "HIR"Lưu Manh"NOR") hay trét lên mặt, làm cho bản thân nam không ra nam nữ không ra nữ.",
             "敷面粉" :   "Những thứ đồ này có thể tìm ở "HIR"Linh Cốc Động"NOR" phải không nhỉ ?",
             "红印纸" :   "Những thứ đồ này có thể tìm ở "HIR"Linh Cốc Động"NOR" phải không nhỉ ?",
             "发刷" :   "Những thứ đồ này có thể tìm ở "HIR"Linh Cốc Động"NOR" phải không nhỉ ?",
             "粉扑" :   "Lưu ý rằng "HIR"Heo Rừng"NOR" có rất nhiều Hồng Phấn Phác trên mặt? Hẳn là có liên quan tới nhau.。",
             "发夹" :   "Ta nhớ đã từng thấy ở "HIR"Trường bạch sơn"NOR" thấy một ít yêu quái mang theo vật này...",
             "铜镜" :   ""HIR"Linh Cốc Động"NOR" bên trong có rất nhiều gương đồng.",
             "手镜" :   "Ta nhớ đã từng thấy ở "HIR"Trường bạch sơn"NOR" thấy một ít yêu quái mang theo vật này...",
             "锣" :   "Một ít "HIR"Lang yêu quái"NOR" liền mang theo .",
             "鼓" :   "Một ít "HIR"Hổ Yêu Quái"NOR" sẽ mang theo .",
             "钹" :   ""HIR"Dã Trư Yêu"NOR" có thể mang theo bạt .",
             "梆子" :   ""HIR"Cường Đạo"NOR" cũng thích đùa bỡn một cái bang tử làm tự ngu tự nhạc .",
             "笛子" :   "Binh lính "HIR"Tần Quốc"NOR" thích thổi sáo để giải trí .",
             "唢呐" :   ""HIR"Dã Trư Yêu"NOR" có thể mang theo tỏa nột .",
             "萧" :   ""HIR"Tần Quốc"NOR" có nhạc khí mà binh lính thường dùng để giải trí.",
             "竽" :   ""HIR"Tần Quốc"NOR" có nhạc khí mà binh lính thường dùng để giải trí.",
             "筝" :   ""HIR"Tần Quốc"NOR" có nhạc khí mà binh lính thường dùng để giải trí.",
             "琵琶" :   "Tới "HIR"Đông Hải"NOR" có thể tìm được loại nhạc khí này",
             "二胡" :   ""HIR"Yên Quốc"NOR" người cũng yêu lạp nhị hồ .",
             "“一筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“二筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“三筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“四筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“五筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“六筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“七筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“八筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“九筒”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“一条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“二条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“三条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“四条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“五条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“六条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“七条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“八条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“九条”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“一万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“二万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“三万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“四万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“五万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“六万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“七万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“八万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“九万”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“东风”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“南风”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“西风”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“北风”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“红中”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“发财”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“白板”" :   "Những người nghiện cờ bạc, chẳng hạn như "HIR"Côn Đồ"NOR" sẽ có rất nhiều thứ cần thiết!",
             "“帅”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“仕”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“相”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“車”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“馬”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“炮”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“兵”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“将”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“士”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“象”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“车”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“马”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“砲”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "“卒”" :   "Hãy đi "HIR"Yên, Triệu, Tần Trường Thành"NOR" để tìm một ít cờ về.",
             "黑棋子" :   "Ta còn nhớ "HIR"Tướng Quân Cổ Mộ"NOR" ắt hẳn sẽ có.",
             "白棋子" :   "Ta còn nhớ "HIR"Tướng Quân Cổ Mộ"NOR" ắt hẳn sẽ có.",
             "竹子" :   ""HIR"Đạo Thảo Nhân"NOR" trên người cũng có rất nhiều?",
             "竹蜻蜓" :   "Những "HIR"Hầu Tử"NOR" nghịch ngợm thường sẽ trộm đi món đồ chơi của đứa trẻ .",
             "小风车" :   "Những thứ đáng hận kia chính là "HIR"Lang Nhân"NOR" thường sẽ trộm đi món đồ chơi của đứa trẻ .",
             "小泥人" :   "Một ít "HIR"Thảo Khẩu"NOR" thường sẽ dùng một ít tiểu nê người lừa gạt đứa trẻ làm tiếp đích .", 
             "泥块" :   "ĐI tìm "HIR"Đạo Thảo Nhân"NOR" trên người cũng có rất nhiều?",
             "冰块" :   "Đi "HIR"Đông Hải"NOR" hẳn có thể tìm được khối băng đấy?",
             "雕刻刀" :   ""HIR"Thạch Sư"NOR" cùng "HIR"Thạch Hổ"NOR" trong cơ thể ắt hẳn đang cất giấu một thanh điêu khắc đao .",
             "柳条" :   "Ta còn nhớ ở "HIR" đường gia Trang Viên Loan Đạo"NOR" có thể tìm thấy Liễu Điều.",
             "木板" :   "Mộc Bản hẳn là đang ở "HIR" Trịnh Quốc Cừ "NOR" rất nhiều đó?",
             "玉石" :   ""HIR"Thạch Sư Thạch Hổ "NOR"trong cơ thể có một dấu Ngọc Thạch làm lay động lực đẩy nguyên khí.",
]);
//变身卡
static string *nCard = ({"0010","0011","0050","0051","0052","0053","0101","0102","0150",
			"0151","0152","0200","0201","0202","0250","0251","0252","8011",
			"8010","0300","0301","0302","0303","0304","0350","0351","0352",
			"0400","0401","0402","0450","0500","0502","0550","0551","0552",
		});
		
// 函数：显示提示信息(场景公用)
string get_gift_tips( string id )
{
        return TipsTable[id];
}
//获得随机变身卡
string get_random_card()
{
	return "item/54/"+nCard[random(sizeof(nCard))];
}
